# Generated by Django 3.1.3 on 2020-12-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201208_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
