# Generated by Django 3.1.3 on 2020-12-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201211_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged',
        ),
    ]
