# Generated by Django 3.0.8 on 2021-05-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
